# Generated by Django 4.0.4 on 2022-06-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
