# Generated by Django 4.0.4 on 2022-06-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisements_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='description',
            field=models.TextField(default='', verbose_name='описание'),
        ),
    ]
