# Generated by Django 4.0.4 on 2022-06-22 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisements',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
