# Generated by Django 4.0.4 on 2022-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_advertisements_created_at_advertisements_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
